# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 331c79dea87d0c3092d0b9c0c1658e6a31196f140a444e76c2c8d8458a8548f7c88a1a329e034e9638c345e047ded632b8cb2577ee6340a396f1f44749107fd5

test:
  secret_key_base: 0cf066dc7f0585a6522b5d65dd277997ee137464e56a3a8126e1ee1f0f129338c253d12f85e5ee6195eba9c585fa47a6468600cced3a36b81c7afdb8bd597df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
